config/routes.rb
DemoApp2::Application.routes.draw do
  devise_for :authors
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :models
  get "start/index"
  resources :articles

  devise_for :users
  get "store/index"
  get "store/show"
  get "index/show"
  resources :recipes do
       collection do
      get :sample
    end
  end

  get "emailrecipe(/:id)(.:format)" => "recipes#email_recipe" , :as => "email_recipe"
  
  get "store/index"
  get "store/show/:id(.:formate)" => "store#show", :as => "show"
  get "recipes/sample" => "recipes#products", :as => "sample"
  get "page/home"
  get "page/about"
  post "page/about"
  get "page/products(/:id)(.:format)" => "page#products", :as => "products"
  post "page/products"
  get "page/services"
  get "start/start"
  

  
get "page/support(/:year(/:month))"  => "page#support", :as => "calendar"

  get "page/faq"
  get "page/contact_us"
  get "page/login"
  get "users/new"
  get "users/list"
  get "users/delete"

  root 'start#start'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
validates_presence_of :name, :ingredients, :made_by
validates_numericality_of :serves, :only_integer => true
validates_uniqueness_of :name

  after_save :send_recipes

  def send_recipes
     logger.info "******************Going to send recipes #{name}"
     if published?
	     User.find_by_newsletter(true).each do |user|
	      	RecipeMailer.send_recipe( id,user ).deliver
	 	 end
     end 
  end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate
  
  def email_recipe
       RecipeMailer.send_recipe( params[:id] ).deliver
       redirect_to recipes_url
  end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)

respond_to do |format|
      format.html
      format.json { render json: @recipes }
      format.xml { render xml: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
   @recipe = Recipe.new
   end

  # GET /recipes/1/edit
  def edit
  end
  
  def sample
@recipe = Recipe.new
    render :new
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :made_by, :ingredients, :last_made, :image, :serves, :cost)
    end

   def authenticate
     authenticate_or_request_with_http_basic do |username , password|
          username == "kishore" && password == "kishore"
  end
end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'shared/form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>
<%= will_paginate @recipes, :class => 'apple_pagination' %>
<table style="border:1px solid green;padding:10px;margin:10px;">
  <thead>
    <tr>
      <th>Name</th>
      <!--<th>Made by</th>
      <th>Ingredients</th>
      <th>Last made</th>-->
      <th>Image</th>
      <th>Serves</th>
      <th>Cost</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody >
    <% @recipes.each do |recipe| %>
      <tr >
        <td><%=link_to recipe.name , recipe %></td>
       <!-- <td><%= recipe.made_by %></td>
        <td><%= truncate(recipe.ingredients) %></td>
        <td><%= recipe.last_made.time_set %></td> -->
        <td><%=link_to 'image' , "assets/#{recipe.image}" %></td>
        <td><%= recipe.serves %></td>
        <td><%= number_to_currency(recipe.cost) %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' },:remote=>true, :class=>'delete_post' %></td>
        <td><%= link_to 'Send Email', email_recipe_path( recipe ) %></td>
        
      </tr>

    <% end %>
  </tbody>
</table>
<%= will_paginate @recipes,:class => 'apple_pagination' %>
<br>
<%= link_to 'sample' , sample_path %><
          
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'shared/form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<div id="select">
<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Made by:</strong>
  <%= @recipe.made_by %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <strong>Last made:</strong>
  <%= @recipe.last_made %>
</p>

<p>
  <strong>Image:</strong>
  <%=image_tag @recipe.image %>
</p>

<p>
  <strong>Serves:</strong>
  <%= @recipe.serves %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @recipe.cost %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
</div>