config/routes.rb
DemoApp2::Application.routes.draw do
  devise_for :authors
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :models
  get "start/index"
  resources :articles

  devise_for :users
  get "store/index"
  get "store/show"
  get "index/show"
  resources :recipes do
       collection do
      get :sample
    end
  end

  get "emailrecipe(/:id)(.:format)" => "recipes#email_recipe" , :as => "email_recipe"
  
  get "store/index"
  get "store/show/:id(.:formate)" => "store#show", :as => "show"
  get "recipes/sample" => "recipes#products", :as => "sample"
  get "page/home"
  get "page/about"
  post "page/about"
  get "page/products(/:id)(.:format)" => "page#products", :as => "products"
  post "page/products"
  get "page/services"
  get "start/start"
  

  
get "page/support(/:year(/:month))"  => "page#support", :as => "calendar"

  get "page/faq"
  get "page/contact_us"
  get "page/login"
  get "users/new"
  get "users/list"
  get "users/delete"

  root 'start#start'

  

end

app/views/shared/_flash.html .erb
<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p><br />.html_safe
<%end%>

<% if flash[:error] %>
  <p class="error" > <%= flash[:error] %></p><br />
<%end%>

app/views/shared/_footer.html.erb
<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->

app/views/shared/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :made_by %><br>
    <%= f.text_field :made_by %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :last_made %><br>
    <%= f.datetime_select :last_made %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :serves %><br>
    <%= f.number_field :serves %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><%=link_to_unless_current "Home", page_home_path %></li>
				<li><%=link_to_unless_current "About", new_recipe_path %></a></li>
				<li><%=link_to_unless_current "Products", products_path %></li>
				<li><%=link_to_unless_current "Recipes", store_index_path %></li>
				<li><%=link_to_unless_current "Articles", articles_path %></li>
				<li><%=link_to_unless_current "Faq's", page_faq_path %></li>
				<li><%=link_to_unless_current "Contact US", page_contact_us_path %></a></li>
				<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
				<li><%=link_to_unless_current "Admin", recipes_path %></a></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->

app/views/shared/_sidebar.html.erb
<h3>Things To Do</h3>
					<%= things_to_do('http://www.google.com' => 'google',
							 calendar_path => 'calendar',
							 'http://www.facebook.com' => 'facebook') %>
					
				<h3>Sponsors</h3>
					<%= image_tag "ad180.png" %><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">LinkedIn</a></li>
						<li><a href="#">Flickr</a></li>
					</ul>