config/routes.rb
DemoApp2::Application.routes.draw do
  devise_for :authors
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :models
  get "start/index"
  resources :articles

  devise_for :users
  get "store/index"
  get "store/show"
  get "index/show"
  resources :recipes do
       collection do
      get :sample
    end
  end

  get "emailrecipe(/:id)(.:format)" => "recipes#email_recipe" , :as => "email_recipe"
  
  get "store/index"
  get "store/show/:id(.:formate)" => "store#show", :as => "show"
  get "recipes/sample" => "recipes#products", :as => "sample"
  get "page/home"
  get "page/about"
  post "page/about"
  get "page/products(/:id)(.:format)" => "page#products", :as => "products"
  post "page/products"
  get "page/services"
  get "start/start"
  

  
get "page/support(/:year(/:month))"  => "page#support", :as => "calendar"

  get "page/faq"
  get "page/contact_us"
  get "page/login"
  get "users/new"
  get "users/list"
  get "users/delete"

  root 'start#start'

  

end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8" />
  <title>kishore's 	<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "screen", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "print", media: "print", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<center>This is kishore new Application!</center>
<div id="wrapper"><!-- #wrapper -->

	<%= render 'shared/navigation' %>
	
	<header><h1><a href="#">On The Radar <%= yield :title %></a></h1>	</header>
	
<section id="main"><!-- #main content and sidebar area -->
<section id="content"><!-- #content -->


<div style="background:#FF00EE">
<%if params[:commit] %>
<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice].html_safe %></p><br />
<%end%>

<% if flash[:error] %>
  <p class="error" > <%= flash[:error].html_safe %></p><br />
<%end%>
<% if flash[:alert] %>
  <p class="error" > <%= flash[:alert].html_safe %></p><br />
<%end%>
<%end%>
</div>
        		<article>
<%= yield %>
</article>

	</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<%= render 'shared/sidebar' %>
		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<%= render 'shared/footer' %>
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

app/views/layouts/recipes.html.erb
 <!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8" />
  <title>kishore's 	<%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "screen", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "print", media: "print", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body style="background:#FFFF00">
<center>This is kishore new Application!</center>
<div id="wrapper"><!-- #wrapper -->

	<%= render 'shared/navigation' %>
	
	<header><h1><a href="#">On The Radar <%= yield :title %></a></h1>	</header>
	
<section id="main"><!-- #main content and sidebar area -->
<section id="content"><!-- #content -->


<div style="background:#FF00EE">
<%if params[:commit] %>
<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice].html_safe %></p><br />
<%end%>

<% if flash[:error] %>
  <p class="error" > <%= flash[:error].html_safe %></p><br />
<%end%>
<%end%>
</div>
        		<article>
<%= yield %>
</article>

	</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<%= render 'shared/sidebar' %>
		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<%= render 'shared/footer' %>
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

app/views/layouts/start.html.erb
 <!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8" />
  <title>kishore's 	<%= yield :title %></title>
  <%= stylesheet_link_tag    "start", media: "screen", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "print", media: "print", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  
</head>
<body>
<center>This is kishore new Application!</center>

        		<article>
<center>
<div id="nav">
<%if author_signed_in? %>
   
    Signed in as <%= current_author.email %>
    <%= link_to 'sign out', destroy_author_session_path %>
 <% else %>
     <%= link_to 'sing up',new_author_registration_path %> <%= link_to 'sign in' , new_author_session_path %>
  <% end %>
</div>
<%= yield %></center>

</article>
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>